openapi: 3.1.0
info:
  title: GPTZero API
  version: 1.0.0
servers:
  - url: https://gptzero-site.netlify.app/api
paths:
  /detect:
    post:
      operationId: detectAIContent
      summary: Detectar si un texto fue generado por IA
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                document:
                  type: string
      responses:
        '200':
          description: Resultado del análisis
          content:
            application/json:
              schema:
                type: object
                properties:
                  fake:
                    type: boolean
                    description: Si el texto fue probablemente generado por IA
                  average_generated_prob:
                    type: number
                    format: float
                    description: Probabilidad promedio de generación por IA
